# Autogenerated by nbdev

d = { 'settings': {'branch': '', 'doc_baseurl': '/', 'doc_host': 'https://.github.io', 'git_url': 'https://github.com//', 'lib_path': ''},
  'syms': {'nbdev_cards.core': {'nbdev_cards.core.foo': ('core.html#foo', 'nbdev_cards/core.py')}, 'nbdev_cards.setup': {}}}
